kaihatsu/TutoRealCS/TutoRealCS/Models/StandByListViewModel.cs
using TutoRealBE;
using TutoRealBE.Context;
using TutoRealBE.Result;

namespace TutoRealCS.Models
{
    public class StandByListViewModel
    {
        #region 検索条件

        /// <summary>
        /// 検索条件リスト
        /// </summary>
        public StandByConditionContext Condition { get; set; } = new StandByConditionContext();

        #endregion
        #region 画面表示
        /// <summary>
        /// 検索結果
        /// </summary>
        public List<StandByListResult> DataList { get; set; } = new List<StandByListResult>();

        #endregion
    }
}

kaihatsu/TutoRealCS/TutoRealCS/Controllers/StandByController.cs
using TutoRealCS.Models;
using Microsoft.AspNetCore.Mvc;
using CFL = TutoRealCommon.CommonFunctionLibrary;
using CC = TutoRealCommon.CommonConst;
using CE = TutoRealBE.Entity.CommonEntity;
using Microsoft.Data.SqlClient;
using System.Text;
using System.Data;
using TutoRealBE.Context;
using TutoRealBE.Result;
using TutoRealBF;

namespace TutoRealCS.Controllers
{
    public class StandByController : BaseController
    {
        private readonly ITutoRealBaseBF _baseBF;

        public StandByController(ITutoRealBaseBF baseBF) : base(baseBF)
        {
            _baseBF = baseBF;
        }

        [HttpGet]
        public IActionResult Index()
        {
            StandByListViewModel retVM = new StandByListViewModel();
            return View(CC.VIEWNAME.STANDBYLIST, retVM);
        }
        [HttpPost]
        public async Task<IActionResult> Search(StandByListViewModel formData)
        {
            formData.DataList.Clear();
            StandByConditionContext context = new StandByConditionContext()
            {
                EmpId7 = formData.Condition.EmpId7,
                Name = formData.Condition.Name,
                StartDate = formData.Condition.StartDate,
                EndDate = formData.Condition.EndDate,
                ProcessKbn = CE.ProcessKbn.Select
            };

            //共通BFの呼び出し
            var result_bf = await _baseBF.Invoke(context);

            if (result_bf.Count() == 0)
            {
                //入力したIDがDBにない
                return View(formData);
            }
            else
            {
                //DB取得結果
                List<StandByListResult> result = (List<StandByListResult>)result_bf;
                formData.DataList = new List<StandByListResult>();
                foreach (var row in result)
                {
                    StandByListResult rowdata = new StandByListResult()
                    {
                        EmpId7 = row.EmpId7,
                        SeiKanji = row.SeiKanji,
                        MeiKanji = row.MeiKanji,
                        StartDate = row.StartDate,
                        EndDate = row.EndDate,
                        MailAddress = row.MailAddress,
                    };
                    formData.DataList.Add(rowdata);
                }

                return View(CC.VIEWNAME.STANDBYLIST, formData);
            }

        }
    }
}

kaihatsu/TutoRealCS/TutoRealCS/Views/StandBy/StandByList.cshtml
@* ViewModelを指定する *@
@model StandByListViewModel
@{
    ViewData["Title"] = "戻り待機者一覧";
}

@section Styles {
    <link rel="stylesheet" href="~/css/StandBy/standbyList.css" asp-append-version="true" />
}

@section Scripts {
    <script src="~/js/StandBy/standbylist.js"></script>
}

<form class="card startform" asp-controller="StandBy" asp-action="Search" method="POST">
    @* 画面全体 *@
    <div class="maincontents-layout">
        @* 検索条件 *@
        <div class="card">
            <label class="lblRegion">検索条件</label>
            <div class="divRegion">
                <table class="tableCommon">
                    <tr class="trFixHeight">
                        <td class="tdLabel">社員番号：</td>
                        <td class="tdItem">
                            <input type="text" asp-for="Condition.EmpId7" class="textbox w100" maxlength="7" />
                        </td>
                        <td class="tdLabel">姓名カナ：</td>
                        <td class="tdItem">
                            <input type="text" asp-for="Condition.Name" class="textbox w240" maxlength="13" />
                        </td>
                        <td class="tdLabel">待機期間：</td>
                        <td class="tdItem">
                            <div class="rowContents">
                                <input asp-for="Condition.StartDate" class="w_calendar" type="date" />
                                ～
                                <input asp-for="Condition.EndDate" class="w_calendar" type="date" />
                                <button class="btnSearch w120">検索</button>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        @* 検索結果 *@
        <table class="DataGrid">
            <thead>
                <tr>
                    <th class="w100">社員番号</th>
                    <th class="w240">姓名</th>
                    <th class="w120">待機開始日</th>
                    <th class="w120">待機終了日</th>
                    <th>メールアドレス</th>
                </tr>
            </thead>
        </table>
        <div class="data_grid">
            <table class="DataGrid">
                <tbody>
                    @foreach (var datas in Model.DataList)
                    {
                        <tr tabindex="0">
                            <td class="w100">@datas.EmpId7</td>
                            <td class="w240 gridLeft">@datas.SeiKanji @datas.MeiKanji</td>
                            <td class="w120">@datas.StartDateYMD</td>
                            <td class="w120">@datas.EndDateYMD</td>
                            <td class="gridLeft">@datas.MailAddress</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>